[package]
name = "multisig_core"
version = "0.1.0"
edition = "2024"

[dependencies]
nssa_core = { git = "https://github.com/logos-blockchain/lssa.git", rev = "767b5afd388c7981bcdf6f5b5c80159607e07e5b" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
borsh = "1.5.7"
sha2 = { version = "0.10", default-features = false }
